### PR TITLE
Chester's updates from 2020-02-04

### PR DESCRIPTION
**Pull request by ismayc**

### CODE REVIEW

**Comment by ismayc** [comment]
Ah, crud. This PR is terrible since I removed decktape and built the PDF using {pagedown} instead. The relevant file to review is just the Rmd [here](https://github.com/ismayc/talks/pull/4/files#diff-1a012440e9fd8ada6a0345b40f0b6adb27de4de6d18541f3c63194b5c0456806).

**Comment by ismayc** [comment]
Here are the slides too: https://csp2021.netlify.app/slide_deck.html. I've updated them to refer to the `csp-02-03` branch, but we can switch that to master as well if we need a backup after we merge everything in.

**Review by jminnier — COMMENTED** [review]
super

**Comment by jminnier** [comment]
I've never "reviewed" before, sorry, maybe wasn't supposed to merge =P

**Pull request merged**
